// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  tutorialSidebar: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      collapsed: false,
      items: [
        // {
        //   type: 'doc',
        //   label: "About PANDA Terminal",
        //   id: 'introduction/about-pt'
        // }
        'introduction/getting-started']
    },
    {
      type: "category",
      label: "Workbench",
      collapsible: false,
      link: { type: 'doc', id: 'workbench/overview/index' },
      collapsed: false,
      items: [
        // {
        //   type: "category",
        //   label: "Overview",
        //   link: { type: 'doc', id: 'workbench/overview/index' },
        //   collapsible: true,
        //   collapsed: false,
        //   items: ['workbench/overview/navigating-the-chart-interface']
        // },
        'workbench/overview/navigating-the-chart-interface',
        'workbench/workbench-cmds', {
          type: "category",
          label: "Using The Workbench",
          link: { type: 'doc', id: 'workbench/using-the-workbench/using-the-wb' },
          collapsible: true,
          collapsed: false,
          items: ['workbench/using-the-workbench/charting-tools',
            {
              type: "category",
              label: "Studies",
              link: { type: 'doc', id: 'workbench/using-the-workbench/studies-metrics/index' },
              collapsible: true,
              collapsed: false,
              items: ['workbench/using-the-workbench/studies-metrics/custom-metrics/onchain-metrics',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/orderflow-metrics',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/orderbook-metrics',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/exchange-metrics',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/jlabs-analytics',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/jlabs-models',
                'workbench/using-the-workbench/studies-metrics/custom-metrics/jlabs-token-ratings'
              ]
            },
            'workbench/using-the-workbench/panda-intel'
          ]
        },
        'workbench/saving-resaving-a-workbench',
        {
          type: 'category',
          label: "Sharing",
          link: { type: "doc", id: "workbench/sharing/index" },
          collapsible: true,
          collapsed: false,
          items: ['workbench/sharing/sharing-in-workbench', 'workbench/sharing/sharing-in-panda-intel']
        }]
    },
    {
      type: "category",
      label: "Screener",
      link: { type: 'doc', id: 'screener/overview' },
      collapsible: false,
      collapsed: false,
      items: [
        'screener/screener-commands', 'screener/creating-a-screener',
        {
          type: "category",
          label: "Screener Filters",
          collapsible: true,
          collapsed: false,
          link: { type: 'doc', id: 'screener/screener-filters/index' },
          items: ['screener/screener-filters/onchain-metrics',
            'screener/screener-filters/offchain-metrics',
            'screener/screener-filters/fundamental-metrics']
        },
      ]
    },
    {
      type: 'category',
      label: "Dashboard",
      collapsible: false,
      collapsed: false,
      link: { type: 'doc', id: 'dashboard/overview' },
      items: [
        // 'dashboard/overview',
        'dashboard/dashboard-commands',
        'dashboard/creating-a-dashboard',
        {
          type: 'category',
          label: "Customizing a Dashboard",
          collapsible: true,
          collapsed: false,
          link: { type: "doc", id: "dashboard/customizing-a-dashboard/index" },
          items: ['dashboard/customizing-a-dashboard/adding-a-workbench-to-dashboard',
            'dashboard/customizing-a-dashboard/adding-a-screener-to-dashboard',
            'dashboard/customizing-a-dashboard/adding-trades-to-dashboard',
            'dashboard/customizing-a-dashboard/adding-orderbook-to-dashboard'
          ]
        },
        {
          type: "category",
          label: "Two-Way Syncing",
          collapsible: true,
          collapsed: false,
          link: { type: 'doc', id: 'dashboard/two-way-syncing/index' },
          items: ['dashboard/two-way-syncing/dashboard-to-workbench', 'dashboard/two-way-syncing/workbench-to-dashboard']
        },
        'dashboard/explorer',
        {
          type: 'category',
          label: 'Publishing',
          collapsible: true,
          collapsed: false,
          link: { type: 'doc', id: 'dashboard/publishing/index' },
          items: ['dashboard/publishing/choosing-audience']
        }
      ]
    },
    {
      type: "category",
      label: "Trading",
      collapsible: false,
      collapsed: false,
      items: [{
        type: 'category',
        label: "Centralised Exchanges (CEX)",
        collapsible: true,
        collapsed: false,
        link: { type: 'doc', id: 'trading/centralised-exchange/index' },
        items: [{
          type: 'category',
          label: "Setting up your Account & API Keys",
          collapsible: true,
          collapsed: false,
          link: { type: 'doc', id: 'trading/centralised-exchange/setting-up-your-account-and-api-keys/index' },
          items: ['trading/centralised-exchange/setting-up-your-account-and-api-keys/how-to-connect-your-bybit-exchange-account',
            'trading/centralised-exchange/setting-up-your-account-and-api-keys/setting-up-your-bybit-api-keys'
          ]
        }, 'trading/centralised-exchange/trading']
      },
      {
        type: 'category',
        label: "Decentralised Exchanges (DEX)",
        collapsible: true,
        collapsed: false,
        link: { type: 'doc', id: 'trading/decentralised-exchange/index' },
        items: ['trading/decentralised-exchange/connecting-your-wallet',
          'trading/decentralised-exchange/adjust-rpcs-on-metamask',
          'trading/decentralised-exchange/swap-tokens',
          'trading/decentralised-exchange/custom-tokens'
        ]
      }
      ]
    },
    {
      type: 'category',
      label: "Community",
      link: { type: 'doc', id: "community/overview" },
      collapsible: false,
      collapsed: false,
      items: [
        // 'community/overview', 
        {
          type: 'category',
          label: 'Building a Community',
          collapsible: true,
          collapsed: false,
          link: { type: 'doc', id: 'community/building-a-community/index' },
          items: [{
            type: 'category',
            label: 'Creating a Community',
            collapsible: true,
            collapsed: false,
            link: { type: 'doc', id: 'community/building-a-community/creating-a-community/index' },
            items: ['community/building-a-community/creating-a-community/admin-control-and-access']
          }, 'community/building-a-community/managing-a-community']
        },
        'community/publishing-in-community',
        'community/access-and-clone-publishes'
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
